### Health
GET http://localhost:8080/api/v1/health

### Create
POST http://localhost:8080/api/v1/artwork
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzMwNDM1MjM0fQ.HXkbYzYRi8K0LmoW6zIGM6mFVxI0ekiBd3dtQm8Ru9w

{
    "title": "Image 1",
    "description": "Description 1"
}


### List
GET http://localhost:8080/api/v1/artwork


### Get
GET http://localhost:8080/api/v1/artwork/f12f900c-1459-4694-abea-d9709951d96f


### Delete
DELETE http://localhost:8080/api/v1/artwork/98afe6e3-ea0b-4d92-a504-0fc44f5e4584
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzMwNDM1MjM0fQ.HXkbYzYRi8K0LmoW6zIGM6mFVxI0ekiBd3dtQm8Ru9w


### Update
PATCH http://localhost:8080/api/v1/artwork/08b7a0fe-fa30-46df-b10b-feb089f7fc25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzMwNDM1MjM0fQ.HXkbYzYRi8K0LmoW6zIGM6mFVxI0ekiBd3dtQm8Ru9w

{
    "title": "Title Updated Second Time"
}


### Login
POST http://127.0.0.1:8080/api/v1/login
Content-Type: application/x-www-form-urlencoded

username=johndoe&password=secret


### Signup
POST http://127.0.0.1:8080/api/v1/signup
Content-Type: application/json

{
    "username": "johndoe",
    "password": "secret"
}
